template_path: InternetGateways.py
sceptre_user_data:
  igw_vpcid: !stack_output sceptreprj-dev/02-Network/02-vpc.yaml::vpcidoutput
  igw_prefix: igwnew
  igw_params_attachment_prefix: igwvpcattach
  igw_params_igwid_prefix: igwidoutput
