template_path: CloudFronts.py
sceptre_user_data:
  distribution_params_s3bucketname: !stack_output sceptreprj-dev/01-S3/01-adminS3Bucket.yaml::admins3bucketnameoutput
  distribution_params_s3httpurl: !stack_output sceptreprj-dev/01-S3/01-adminS3Bucket.yaml::admins3httpurloutput
  distribution_params_s3hostingrootfile: !stack_output sceptreprj-dev/01-S3/01-adminS3Bucket.yaml::admins3hostingrootfileoutput
  distribution_params_certificatearn: arn:aws:acm:us-east-1:850600621207:certificate/8dff5516-02e5-4b19-944e-4814469b738c
  distribution_params_distributionid_prefix: admins3distributionidoutput
  distribution_params_domainname_prefix: admins3distributiondomainnameoutput
