template_path: S3Publics.py
sceptre_user_data:
  s3_bucket: adminSmartcheck
  s3_policy: adminBucketPolicy
  s3_hosting_maindomain: smartcheck.gq
  s3_hosting_subdomain_url: admin   # customization available
  s3_hosting_rootfile: index.html   # customization available
  s3_params_s3bucketname_prefix: admins3bucketnameoutput
  s3_params_s3httpurl_prefix: admins3httpurloutput
  s3_params_s3hostingrootfile_prefix: admins3hostingrootfileoutput
