template_path: Route53RecordSets.py
sceptre_user_data:
  recordset_params_maindomain: smartcheck.gq
  recordset_params_cloudfronthostedzoneid: Z2FDTNDATAQYW2
  recordset_params_recordsetname: !stack_output sceptreprj-dev/01-S3/01-wwwS3Bucket.yaml::wwws3bucketnameoutput
  recordset_params_distibutiondomainname: !stack_output sceptreprj-dev/01-S3/01-wwwS3BucketCDN.yaml::wwws3distributiondomainnameoutput
  recordset_params_recordtype: A
  recordset_params_recordsetid_prefix: wwws3recordsetidoutput
