template_path: S3Privates.py
sceptre_user_data:
  s3_bucket: backendSmartcheck
  s3_hosting_maindomain: smartcheck.gq
  s3_hosting_subdomain_url: backend   # customization available
  s3_params_s3bucketname_prefix: backends3bucketnameoutput
  s3_params_s3httpurl_prefix: backends3httpurloutput
