template_path: EC2s.py
sceptre_user_data:
  ec2_prefix: ec2new
  ec2_params_instance_imageid: ami-02c9728b733d27242
  ec2_params_instance_type: t2.micro
  ec2_params_instance_keyname: smartcheckkey    # customization available
  ec2_params_instance_sg_sgid: !stack_output sceptreprj-dev/02-Network/02-sg.yaml::sgidoutput
  ec2_params_instance_publicip_access: true
  ec2_params_instance_deviceindex: 0
  ec2_params_instance_deleteontermination: true
  ec2_params_instance_publicsubnet1_subnetid: !stack_output sceptreprj-dev/02-Network/02-publicSubnet1.yaml::publicsubnet1idoutput
  ec2_params_userdata_dbhost: !stack_output sceptreprj-dev/03-DB/03-dbCluster.yaml::dbendpoint
  ec2_params_userdata_dbusername: !stack_output sceptreprj-dev/03-DB/03-dbCluster.yaml::dbusername
  ec2_params_userdata_dbuserpassword: !stack_output sceptreprj-dev/03-DB/03-dbCluster.yaml::dbuserpassword
  