template_path: Route53RecordSets.py
sceptre_user_data:
  recordset_params_maindomain: smartcheck.ml
  recordset_params_cloudfronthostedzoneid: Z2FDTNDATAQYW2
  recordset_params_recordsetname: !file_contents sceptreprj-dev_outputs.json
  recordset_params_distibutiondomainname: !stack_output sceptreprj-backend/01-ApiGateway/01-apigatewayhttpsdistribution.yaml::apigatewayhttpsdistdomainnameoutput
  recordset_params_recordtype: A
  recordset_params_recordsetid_prefix: backendapigatewayrecordsetidoutput
