CREATE TABLE `applicants` (
  `phoneNo` varchar(16) NOT NULL,
  `curriculumNo` int(10) NOT NULL,
  `applicantName` text NOT NULL,
  `affiliation` text NOT NULL,
  `department` text NOT NULL,
  `position` text NOT NULL,
  `birthDate` text NOT NULL,
  `email` text NOT NULL,
  `otherContact` text NOT NULL,
  `job` text NOT NULL,
  `purposeSelection` text NOT NULL,
  `competencyForJava` text NOT NULL,
  `competencyForWeb` text NOT NULL,
  `projectExperience` text NOT NULL,
  `careerDuration` text NOT NULL,
  `purposeDescription` text NOT NULL,
  `agreeWithFullAttendance` text NOT NULL,
  `agreeWithPersonalinfo` text NOT NULL,
  `agreeWithGuideInfo` text NOT NULL,
  `applicationConfirm` text NOT NULL,
  `recommender` text,
  `howToFindOut` text,
  `insertedTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedTimestamp` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`phoneNo`,`curriculumNo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;