project_code: sceptreprj-dev
region: ap-northeast-2

# certificatearn: arn:aws:acm:us-east-1:458431035434:certificate/deabb27a-be85-4135-963a-d9c74d54fb3f
# maindomain: smartcheck.ml
# hostedzoneid: Z38HJIDXJR4H59