template_path: Subnets.py
sceptre_user_data:
  subnet_vpcid: !stack_output sceptreprj-dev/02-Network/02-vpc.yaml::vpcidoutput
  subnet_prefix: privatesubnet1
  subnet_params_cidrblock: 10.0.1.0/24    # customization available
  subnet_params_access: -private
  subnet_params_azlocation: ap-northeast-1a   # customization available
  subnet_params_subnetid_prefix: privatesubnet1idoutput
