template_path: RouteTables.py
sceptre_user_data:
  rtb_vpcid: !stack_output sceptreprj-dev/02-Network/02-vpc.yaml::vpcidoutput
  rtb_params_public_prefix: publicrtb
  rtb_params_public_access: -public
  rtb_params_private_prefix: privatertb
  rtb_params_private_access: -private
  rtb_params_associate_publicsubnet1_prefix: publicsubnet1
  rtb_params_associate_publicsubnet1_subnetid: !stack_output sceptreprj-dev/02-Network/02-publicSubnet1.yaml::publicsubnet1idoutput
  rtb_params_associate_privatesubnet1_prefix: privatesubnet1
  rtb_params_associate_privatesubnet1_subnetid: !stack_output sceptreprj-dev/02-Network/02-privateSubnet1.yaml::privatesubnet1idoutput
  rtb_params_associate_privatesubnet2_prefix: privatesubnet2
  rtb_params_associate_privatesubnet2_subnetid: !stack_output sceptreprj-dev/02-Network/02-privateSubnet2.yaml::privatesubnet2idoutput
  rtb_params_publicrtbid_prefix: publicrtbidoutput
  rtb_params_privatertbid_prefix: privatertbidoutput
  